### ISSUE TITLE
Allow Babel to be configured in package.json

### ISSUE THREAD

**Issue by harmenjanssen** [grrr-amsterdam/gulpfile#9]
In an attempt to have a little less rc files, configs and whatnot in the root of my projects, I would like to be able to configure Babel from `package.json`.

See also: https://babeljs.io/docs/usage/babelrc/#use-via-package-json

Right now Gulp complains: _Warning: No JavaScript will be built, since there's no `.babelrc` file present_

**Comment by schoenkaft** [comment]
We also have the (optional) `.eslintrc` and `.sass-lint.yml`, which aren't going into any `package.json` or `gulp.json`, since they're way to big (and Yaml). I get that having lots of different dot and non-dot files can be a (minor) pain, but it's usually a bit inevitable. We have files like `.editorconfig`, `Capfile`, `Gemfile`, `Gemfile.lock` etc... as well, which aren't going anywhere as wel...

Furthermore all other configuration is specified in the `gulp.json` file. For example the `autoprefixer` config (which is also optional though, since we have sensible defaults). I don't feel the `package.json` is the place where config likes this needs to be done, especially since we have an actual config file for the build process. Babel of course can only rely on having an `package.json`, so I guess that's why they allow you to do so.

If you update to `v1.0.13` however, you can specify it in the `package.json`. Specifying it in the `gulp.json` is also possible from now on, and I've updated the `README`.

PS: this didn't work out of the box, since we use Babel to transpile `grrr-gulpfile` itself, and therefore we had to specify the `.babelrc` file explicitly.

**Comment by harmenjanssen** [comment]
You can configure `eslint` in `package.json` as well! (https://eslint.org/docs/user-guide/configuring) 
But I get your point. Honestly this is also why it still irks me a bit to rely on both Ruby and Node tools in the build/deploy chain. Talk about tool fatigue!

Anyways, I was trying to insert this Gulpfile in an existing personal project that already had Babel configured in `package.json`, that's how I noticed.
Thanks for the explanation and the update!
